---
#
# Ansible managed
#
repository:
  description: Install and configure harbor on your system.
  homepage: https://robertdebock.nl/
  topics: harbor, ansible, molecule, tox, playbook, hacktoberfest
